language: go

go:
  - "1.x"
  - "1.12"
  - "1.12.x"
  - master

before_install:
  - go get -t -v ./...

install:
  - go get -v golang.org/x/lint/golint

script:
  - go test -v -coverprofile=coverage.txt -covermode=set ./...
  - golint -set_exit_status ./...